import 'meal.dart';
import 'meal_types.dart';

final categoriesMeal = [
  Category(
    name: 'Italian',
    imageurl: 'assets/categorymealimg/italian.jpg',
    id: 'type1',
  ),
  Category(
    name: 'Mexican',
    imageurl: 'assets/categorymealimg/mexican.jpg',
    id: 'type2',
  ),
  Category(
    name: 'French',
    imageurl: 'assets/categorymealimg/french.jpg',
    id: 'type3',
  ),
  Category(
    name: 'Thai',
    imageurl: 'assets/categorymealimg/thai.jpg',
    id: 'type4',
  ),
  Category(
    name: 'Quick & Easy',
    imageurl: 'assets/categorymealimg/quickneasy.jpg',
    id: 'type5',
  ),
  Category(
    name: 'Continental',
    imageurl: 'assets/categorymealimg/continental.jpg',
    id: 'type6',
  ),
  Category(
    name: 'Exotic',
    imageurl: 'assets/categorymealimg/exotic.jpg',
    id: 'type7',
  ),
  Category(
    name: 'Light & Lovely',
    imageurl: 'assets/categorymealimg/lightnlovely.jpg',
    id: 'type8',
  ),
  Category(
    name: 'Nepali',
    imageurl: 'assets/categorymealimg/momos.jpg',
    id: 'type9',
  ),
  Category(
    name: 'Summer',
    imageurl: 'assets/categorymealimg/summer.jpg',
    id: 'type10',
  ),
  Category(
    name: 'Breakfast',
    imageurl: 'assets/categorymealimg/breakfast.jpg',
    id: 'type11',
  ),
  Category(
    name: 'Japanese ',
    imageurl: 'assets/categorymealimg/japnese.jpg',
    id: 'type12',
  ),
  Category(
    name: 'Middle Eastern  ',
    imageurl: 'assets/categorymealimg/middleastern.jpg',
    id: 'type13',
  ),
  Category(
    name: 'Pasta',
    imageurl: 'assets/categorymealimg/pasta.jpg',
    id: 'type14',
  ),
  Category(
    name: 'Indian',
    imageurl: 'assets/categorymealimg/indian.jpg',
    id: 'type15',
  ),
  Category(
    name: 'Vegeterian',
    imageurl: 'assets/categorymealimg/veges.jpg',
    id: 'type16',
  ),
  Category(
    name: 'Smoothie',
    imageurl: 'assets/categorymealimg/smoothie.jpg',
    id: 'type17',
  ),
  Category(
    name: 'Lunch',
    imageurl: 'assets/categorymealimg/lunch.jpg',
    id: 'type18',
  ),
];
final dummymeal = [
  Meal(
    price: '70',
    serving: 1,
    calorie: '300',
    id: 'm1',
    name: 'Spaghetti with Tomato Sauce',
    ingredients: [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)'
    ],
    steps: [
      'Cut the tomatoes and the onion into small pieces.',
      'Boil some water - add salt to it once it boils.',
      'Put the spaghetti into the boiling water - they should be done in about 10 to 12 minutes.',
      'In the meantime, heaten up some olive oil and add the cut onion.',
      'After 2 minutes, add the tomato pieces, salt, pepper and your other spices.',
      'The sauce will be done once the spaghetti are.',
      'Feel free to add some cheese on top of the finished dish.'
    ],
    imageurl: 'assets/dummymealimg/Spaghetti.jpg',
    categories: [
      'type1',
      'type5',
    ],
    duration: 24,
  ),
  Meal(
    price: '110',
    calorie: '400',
    serving: 1,
    id: 'm2',
    categories: [
      'type6',
      'type8',
    ],
    name: 'Toast Hawaii',
    imageurl: 'assets/dummymealimg/toast-hawaii.jpg',
    duration: 10,
    ingredients: [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    steps: [
      'Butter one side of the white bread',
      'Layer ham, the pineapple and cheese on the white bread',
      'Bake the toast for round about 10 minutes in the oven at 200°C'
    ],
  ),
  Meal(
    price: '15',
    calorie: '250',
    serving: 2,
    id: 'm3',
    categories: [
      'type5',
      'type2',
    ],
    name: 'Classic Hamburger',
    imageurl: 'assets/dummymealimg/hamburger.jpg',
    duration: 45,
    ingredients: [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns'
    ],
    steps: [
      'Form 2 patties',
      'Fry the patties for c. 4 minutes on each side',
      'Quickly fry the buns for c. 1 minute on each side',
      'Bruch buns with ketchup',
      'Serve burger with tomato, cucumber and onion'
    ],
  ),
  Meal(
    price: '20',
    calorie: '600',
    serving: 3,
    id: 'm4',
    categories: [
      'type3',
      'type1',
    ],
    name: 'Wiener Schnitzel',
    imageurl: 'assets/dummymealimg/Wiener.jpg',
    duration: 60,
    ingredients: [
      '8 Veal Cutlets',
      '4 Eggs',
      '200g Bread Crumbs',
      '100g Flour',
      '300ml Butter',
      '100g Vegetable Oil',
      'Salt',
      'Lemon Slices'
    ],
    steps: [
      'Tenderize the veal to about 2–4mm, and salt on both sides.',
      'On a flat plate, stir the eggs briefly with a fork.',
      'Lightly coat the cutlets in flour then dip into the egg, and finally, coat in breadcrumbs.',
      'Heat the butter and oil in a large pan (allow the fat to get very hot) and fry the schnitzels until golden brown on both sides.',
      'Make sure to toss the pan regularly so that the schnitzels are surrounded by oil and the crumbing becomes ‘fluffy’.',
      'Remove, and drain on kitchen paper. Fry the parsley in the remaining oil and drain.',
      'Place the schnitzels on awarmed plate and serve garnishedwith parsley and slices of lemon.'
    ],
  ),
  Meal(
    price: '50',
    serving: 2,
    calorie: '400',
    id: 'm5',
    categories: [
      'type11',
      'type8',
    ],
    name: 'Salad with Smoked Salmon',
    imageurl: 'assets/dummymealimg/salmon.jpg',
    duration: 15,
    ingredients: [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper'
    ],
    steps: [
      'Wash and cut salad and herbs',
      'Dice the salmon',
      'Process mustard, vinegar and olive oil into a dessing',
      'Prepare the salad',
      'Add salmon cubes and dressing'
    ],
  ),
  Meal(
    price: '15',
    calorie: '250',
    serving: 1.2,
    id: 'm6',
    categories: [
      'type7',
      'type6',
    ],
    name: 'Delicious Orange Mousse',
    imageurl: 'assets/dummymealimg/orange.jpg',
    duration: 240,
    ingredients: [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    steps: [
      'Dissolve gelatine in pot',
      'Add orange juice and sugar',
      'Take pot off the stove',
      'Add 2 tablespoons of yoghurt',
      'Stir gelatin under remaining yoghurt',
      'Cool everything down in the refrigerator',
      'Whip the cream and lift it under die orange mass',
      'Cool down again for at least 4 hours',
      'Serve with orange peel',
    ],
  ),
  Meal(
    price: '30',
    calorie: '80',
    serving: 1,
    id: 'm7',
    categories: [
      'type1',
      'type4',
      'type5',
    ],
    name: 'Pancakes',
    imageurl: 'assets/dummymealimg/pancake.jpg',
    duration: 20,
    ingredients: [
      '1 1/2 Cups all-purpose Flour',
      '3 1/2 Teaspoons Baking Powder',
      '1 Teaspoon Salt',
      '1 Tablespoon White Sugar',
      '1 1/4 cups Milk',
      '1 Egg',
      '3 Tablespoons Butter, melted',
    ],
    steps: [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
    ],
  ),
  Meal(
    price: '25',
    calorie: '500',
    serving: 1,
    id: 'm8',
    categories: [
      'type9',
      'type8',
      'type15',
    ],
    name: 'Creamy Indian Chicken Curry',
    imageurl: 'assets/dummymealimg/curry.jpg',
    duration: 35,
    ingredients: [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    steps: [
      'Slice and fry the chicken breast',
      'Process onion, garlic and ginger into paste and sauté everything',
      'Add spices and stir fry',
      'Add chicken breast + 250ml of water and cook everything for 10 minutes',
      'Add coconut milk',
      'Serve with rice'
    ],
  ),
  Meal(
    price: '31',
    calorie: '100',
    serving: 2,
    id: 'm9',
    categories: [
      'type11',
      'type12',
      'type3',
    ],
    name: 'Chocolate Souffle',
    imageurl: 'assets/dummymealimg/souffle.jpg',
    duration: 40,
    ingredients: [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    steps: [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
  ),
  Meal(
    price: '13',
    calorie: '300',
    serving: 2,
    id: 'm10',
    categories: ['type6'],
    name: 'Asparagus Salad with Cherry Tomatoes',
    imageurl: 'assets/dummymealimg/asparagus.jpg',
    duration: 30,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
  ),
  Meal(
    price: '130',
    calorie: '600',
    serving: 3,
    id: 'm11',
    categories: ['type13'],
    name: 'Kebabs',
    imageurl: 'assets/dummymealimg/kebab.jpg',
    duration: 50,
    ingredients: [
      'Meat',
      'Marinade',
      'Vegetables',
      'Skewers',
      'fruitsherbs',
      'cheese.',
    ],
    steps: [
      'Choose your meat and cut it into cubes',
      'Make a marinade by mixing together marinade ingredients',
      'Add the meat to the marinade and coat well',
      'Cover and refrigerate for at least 1-2 hours, or overnight for best results.',
      'Soak wooden skewers in water for at least 30 minutes to prevent burning.',
      'Preheat your grill or oven to medium-high heat.',
      'Thread the meat and vegetables onto the skewers.',
      'Brush the kebabs with a bit of oil and place them on the grill or in the oven.',
      'Grill or bake the kebabs for 10-15 minutes,',
      'Serve the kebabs with rice, salad, or other side dishes.',
    ],
  ),
  Meal(
    price: ' 90',
    calorie: '300',
    serving: 1,
    id: 'm12',
    categories: ['type13'],
    name: 'Shawarma ',
    imageurl: 'assets/dummymealimg/shawarma.jpg',
    duration: 30,
    ingredients: [
      'Meat:chicken, beef, or lamb',
      'Pita bread',
      'Vegetables such as lettuce, tomatoes, onions, and cucumber',
      'Sauce include tahini sauce, garlic sauce.',
      'Spices such as cumin, coriander,turmeric.',
    ],
    steps: [
      'Choose your meat and cut it into thin slices',
      'Make a marinade by mixing together yogurt, lemon juice, olive oil, garlic, cumin, coriander, paprika, turmeric, and other spices and herbs of your choice.',
      'Add the meat to the marinade and coat well. Cover and refrigerate for at least 1-2 hours, or overnight for best results.',
      'Preheat your oven to 425°F (218°C) or preheat your grill to medium-high heat.',
      'Thread the meat onto a rotisserie or onto skewers if grilling.',
      'Cook the meat for about 20-30 minutes or until it is fully cooked and tender.',
      'While the meat is cooking, prepare your pita bread and vegetables. Warm the pita bread in the oven or on a grill, and chop your vegetables.',
      'When the meat is cooked, remove it from the rotisserie or skewers and slice it into thin strips.',
      'Assemble your shawarma by placing the sliced meat, vegetables, and sauce of your choice into the pita bread.',
      'Roll up the pita bread and enjoy your delicious shawarma!',
    ],
  ),
  Meal(
    price: '60',
    calorie: '348',
    serving: 4,
    id: 'm13',
    categories: ['type14'],
    name: 'Asian Chicken pasta',
    imageurl: 'assets/dummymealimg/pasta.jpg',
    duration: 25,
    ingredients: [
      '1/4 cup reduced-sodium chicken broth',
      '3 tablespoons reduced sodium soy sauce',
      '2 tablespoons bottled chinese hoisin sauce',
      '1 tablespoon sugar',
      '1 tablespoon vegetable oil',
      '2 teaspoons toasted sesame oil',
      '3 garlic cloves, minced',
      '1 teaspoon fresh ginger, grated',
      '1/2 teaspoon crushed red pepper flakes',
      '1/8 teaspoon black pepper',
      'Salad',
      '12 ounces boneless skinless chicken breasts',
      '4 ounces angel hair pasta',
      '3 medium nectarines or 3 medium peaches, sliced',
      '2 cups baby bok choy, shredded',
      '2 green onions, sliced',
    ],
    steps: [
      'Whisk together the dressing ingredients until very well combined.',
      'Poach chicken breasts in barely simmering water for 12-15 minutes, covered or until no longer pink inside.',
      'Drain and let cool slightly and cut into bite size pieces.',
      'Cook pasta according to package directions.',
      'Drain and toss with 3 tablespoons of dressing.',
      'Plate up pasta on 4 plates and top with chicken, fruit, bok choy and green onions.',
      'Drizzle with remaining dressing.',
    ],
  ),
  Meal(
    price: '40',
    calorie: '398',
    serving: 6,
    id: 'm14',
    categories: ['type14'],
    name: 'Mexican Chicken pasta',
    imageurl: 'assets/dummymealimg/pasta2.jpg',
    duration: 25,
    ingredients: [
      '8 ounces penne pasta',
      '2 cooked chicken breasts',
      '1 (8 3/4 ounce) can whole kernel corn, drained',
      '1 small zucchini, cut in half lengthwise, then sliced',
      '1 -2 stalk celery, sliced thin',
      '1 medium sweet red pepper, sliced',
      '1 medium green pepper, sliced',
      '4 green onions, sliced',
      '1 (4 -7 ounce) can green chilies',
      '1/2-1 cup shredded cheddar cheese ',
      '2 cups lettuce, chopped',
      '1/4 cup chopped cilantro',
      '3/4 cup mayonnaise',
      '1/4 cup sour cream or 1/4 cup yogurt',
      '2 tablespoons ReaLime juice',
      '2 teaspoons sugar',
      '1/2 teaspoon salt',
      '3/4 teaspoon cumin',
      '1/2 teaspoon chili powder',
    ],
    steps: [
      'Cook pasta according to package directions, drain, rinse, and set aside.',
      'Combine all vegetables in a large bowl.',
      'Combine all dressing ingredients; stir thoroughly.',
      'Pour dressing over salad; toss to coat.',
      'Chill 1 hour, then serve.',
    ],
  ),
  Meal(
    price: '14',
    calorie: '398',
    serving: 6,
    id: 'm15',
    categories: [
      'type15',
      'type9',
    ],
    name: 'Rice Pudding',
    imageurl: 'assets/dummymealimg/pudding.jpg',
    duration: 25,
    ingredients: [
      '3/4 cup medium grain rice or 3/4 cup long grain rice',
      '1 1/2 cups water',
      '1/4 teaspoon salt (heaping)',
      '4 cups whole milk (I use 2%)',
      '1/2 cup sugar',
      '1/2 teaspoon vanilla',
      'cinnamon',
    ],
    steps: [
      'Bring rice, water and salt to a boil over med-high heat.',
      'Simmer covered until water has been absorbed (approximately 15 minutes).',
      'Stir in milk and sugar and cook uncovered over medium heat for 30-40 minutes, stirring frequently--especially towards the end of cooking.',
      'The pudding is done when the rice and milk have amalgamated into a thick porridge-like consistency.',
      'DO NOT OVERCOOK or the pudding will be solid instead of creamy once cooled.',
      'Remove from heat and stir in vanilla.',
      'Turn into a bowl or cups.',
      'You can sprinkle cinnamon on the top if you like.',
      'COVER with plastic wrap directly on surface "IF" you don\'t want a skin.',
      'COOL.',
    ],
  ),
  Meal(
    price: '60',
    calorie: '198',
    serving: 6,
    id: 'm17',
    categories: [
      'type16',
      'type9',
    ],
    name: 'Thai Tofu curry',
    imageurl: 'assets/dummymealimg/tofu.jpg',
    duration: 25,
    ingredients: [
      '1 lb firm tofu , drained',
      '1 small butternut squash (about 2 lb/1 kg)',
      '1 tablespoon vegetable oil',
      '1 onion, sliced',
      '2 garlic cloves, minced',
      '2 teaspoons Thai red curry paste',
      '14 ounces light coconut milk',
      '1/2 cup vegetable stock',
      '2 tablespoons soy sauce',
      '1 tablespoon packed brown sugar',
      '1 tablespoon fish sauce or soy sauce',
      '1/2 teaspoon salt',
    ],
    steps: [
      'Pat tofu dry with paper towels; cut into 3/4-inch (2 cm) cubes. Set aside.',
      'Peel and seed squash; cut into 3/4-inch cubes to make 3 cups. Set aside.',
      'In skillet, heat oil over medium heat; cook onion, garlic and curry paste, stirring occasionally, until onion is softened, about 5 minutes.',
      'Add squash, coconut milk, stock, soy sauce, sugar, fish sauce and salt; bring to boil.',
      'Reduce heat to low; partially cover and simmer until squash is almost tender, about 12 minutes.',
      'Add red pepper; simmer for 5 minutes. Add tofu; simmer until heated through, about 2 minutes.',
      '(Make-ahead: Let cool for 30 minutes. Refrigerate, uncovered, in airtight container until cold. ,Cover and refrigerate for up to 1 day. Reheat to continue.)',
      'Stir in cilantro and lime juice; sprinkle with peanuts.',
    ],
  ),
  Meal(
    price: '16',
    calorie: '233',
    serving: 1,
    id: 'm18',
    categories: [
      'type17',
      'type10',
    ],
    name: 'White Russian Smoothie',
    imageurl: 'assets/dummymealimg/cocktai.jpg',
    duration: 25,
    ingredients: [
      '1 scoop vanilla ice cream',
      '3 tablespoons vodka',
      '3 tablespoons Tia Maria (or creme de cacao)',
      '4 ice cubes',
      '1 dash nutmeg, for decoraton',
    ],
    steps: [
      'Put first 3 ingredients in a blender & process SLOWLY until smooth.',
      'Pour in a glass over the ice cubes & sprinkle with the nutmeg.',
    ],
  ),
  Meal(
    price: '24',
    calorie: '139',
    serving: 3,
    id: 'm20',
    categories: [
      'type17',
      'type10',
    ],
    name: 'Strawberry Banana Smoothie',
    imageurl: 'assets/dummymealimg/strawberry.jpg',
    duration: 5,
    ingredients: [
      '250 g strawberries, hulled',
      '1 medium banana, peeled and roughly chopped',
      '300 ml 1% low-fat milk',
      '150 ml natural yoghurt',
      '15 ml spoon clear honey',
    ],
    steps: [
      'Place all the above ingredients into a blender and blend until smooth.',
      'Adjust the sweetness according to taste and pour into serving glasses.',
    ],
  ),
  Meal(
    price: '29',
    calorie: '59',
    serving: 1,
    id: 'm20',
    categories: [
      'type10',
    ],
    name: 'Grape Juice Coctail',
    imageurl: 'assets/dummymealimg/grape.jpg',
    duration: 10,
    ingredients: [
      '1 carton grape juice',
      '1 carton ginger ale',
      'ice cube',
      'lemon slice',
    ],
    steps: [
      'Chill all the ingredients.',
      'Mix together the grape juice and the gingerale.',
      'Top with ice cubes and lemon slices.',
      'Serve immediately.',
    ],
  ),
  Meal(
    price: '30',
    calorie: '288',
    serving: 6,
    id: 'm22',
    categories: [
      'type18',
    ],
    name: 'Scalloped Potatoes',
    imageurl: 'assets/dummymealimg/potatos.jpg',
    duration: 70,
    ingredients: [
      '4 cups thinly sliced potatoes',
      '3 tablespoons butter',
      '3 tablespoons flour',
      '1 1/2 cups milk',
      '1 teaspoon salt',
      '1 dash cayenne pepper',
      '1 cup grated sharp cheddar cheese',
      '1/2 cup grated cheese, to sprinkle on top',
    ],
    steps: [
      'In a small sauce pan, melt butter and blend in flour.',
      'Let sit for a minute.',
      'Add all of cold milk, stirring with a whisk.',
      'Season with salt and cayenne.',
      'Cook sauce on low until smooth and boiling, stirring occasionally with a whisk.',
      'Reduce heat and stir in cheese.',
      'Place a half of the sliced potatoes in a lightly greased one quart casserole dish.',
      'Pour half of cheese sauce over potatoes.',
      'Repeat with second layer of potatoes and cheese sauce.',
      'Sprinkle the remaining cheese on top.',
      'Top with some paprika for color.',
      'Bake uncovered for about 1 hour at 350°F.',
    ],
  ),
  Meal(
    price: '90',
    calorie: '1714',
    serving: 4,
    id: 'm23',
    categories: [
      'type18',
      'type12',
    ],
    name: 'Irish Pub Beef Stew',
    imageurl: 'assets/dummymealimg/beef.jpg',
    duration: 170,
    ingredients: [
      ' 1/2 lbs beef, cut into chunks (splurge on the cut if you can)',
      '1/4 cup butter',
      '1 (10 1/2 ounce) can tomato soup',
      '1 (10 1/2 ounce) can water',
      '4 carrots, cut into chunks',
      '4 large potatoes, cut into chunks (I don\'t peel carrots or spuds but you can if you like)',
      '2 stalks celery, cut into chunks',
      '4 onions, cut into chunks',
      '2 teaspoons salt',
      '1 teaspoon black pepper',
      '1/4 cup fresh parsley, chopped fine',
      '1/4 cup good quality cooking sherry',
      ' 1 teaspoon black pepper',
      '1/4 cup fresh parsley, chopped fine',
      '1/4 cup good quality cooking sherry',
      '2 bay leaves',
    ],
    steps: [
      'Preheat oven to 300F degrees.',
      'In a heavy skillet brown the beef in the butter over medium high heat.',
      'Add the soup and water and stir well.',
      'Add the rest of the ingredients and cook for about 5 minutes, stirring once.',
      'Transfer to a cast iron dutch oven or oven proof pot and cook in the oven, covered for 5 hours, stirring occasionally.',
      'Remove from oven, remove bay leaves and serve with Irish Soda Bread and butter.',
    ],
  ),
];
